name: AestheticSystemsLab
favicon: null
layout_spectrum: 0.72256
typography_spectrum: 0.5
title: Aesthetic Systems Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#275ba7'
    - '#24b0e5'
    - '#8ca7d5'
    - '#c3d8e3'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
