name: AestheticSystemsLab
favicon: null
layout_spectrum: 0.56992
typography_spectrum: 0.15032
title: Aesthetic Systems Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#275ba7'
    - '#24b0e5'
    - '#8ca7d5'
    - '#c3d8e3'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
